import { test, expect } from '@playwright/test'
import { PASSWORD, uniqueEmail } from './helpers'

test('落地页输入 → 注册 → 自动发送 → 历史重命名与删除 → 退出', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '下一站，去哪？' })).toBeVisible()
  await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible()
  await page.waitForFunction(() => Array.from(document.querySelectorAll<HTMLElement>('[style]')).every(el => !el.getClientRects().length || !el.style.opacity || Number(el.style.opacity) >= 0.99))
  await page.screenshot({ path: testInfo.outputPath('landing-desktop.png'), fullPage: true })
  await page.getByRole('textbox').fill('里斯本 5 天')
  await page.getByRole('button', { name: '开始规划' }).click()
  await expect(page).toHaveURL(/\/login\?next=/)
  await expect(page.getByText('登录后将为你规划：「里斯本 5 天」')).toBeVisible()
  await page.getByRole('link', { name: '还没有账号？注册' }).click()
  await page.getByLabel('昵称', { exact: true }).fill('Ann')
  await page.getByLabel('邮箱', { exact: true }).fill(uniqueEmail())
  await page.getByLabel('密码', { exact: true }).fill(PASSWORD)
  await page.getByRole('button', { name: '创建账号', exact: true }).click()
  await expect(page).toHaveURL(/\/chat\/[a-z0-9]+$/)
  await expect(page.getByRole('button', { name: /个人游/ })).toBeVisible()
  await expect(page.getByTestId('live-trip-panel').getByText('完善需求中')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('chat-desktop.png'), fullPage: true })
  await page.reload()
  await expect(page.getByText('里斯本 5 天', { exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: /个人游/ })).toBeEnabled()
  await page.getByRole('button', { name: '历史对话' }).click()
  const drawer = page.getByRole('dialog', { name: '历史对话' })
  await expect(drawer.getByText('里斯本 5 天', { exact: true })).toBeVisible()
  await drawer.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '重命名' }).click()
  await drawer.getByRole('textbox', { name: '重命名' }).fill('葡萄牙之旅')
  await drawer.getByRole('textbox', { name: '重命名' }).press('Enter')
  await expect(drawer.getByText('葡萄牙之旅')).toBeVisible()
  await drawer.getByRole('button', { name: '新对话', exact: true }).click()
  await expect(page).toHaveURL(/\/chat$/)
  await page.getByRole('button', { name: '历史对话' }).click()
  await drawer.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '删除', exact: true }).click()
  await expect(drawer.getByText('还没有对话，从一个目的地开始吧')).toBeVisible()
  await expect(page.getByRole('alertdialog', { includeHidden: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(drawer).toBeHidden()
  await page.getByRole('button', { name: '账号菜单' }).click()
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page).toHaveURL(/localhost:3102\/$/)
  await expect(page.getByRole('link', { name: '登录', exact: true })).toBeVisible()
  await page.goto('/chat')
  await expect(page).toHaveURL(/\/login\?next=%2Fchat$/)
})
