import { test, expect } from '@playwright/test'
import { registerViaUi, expectNoSeriousViolations } from './helpers'
test.use({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true })
test('375px 下落地页无溢出，聊天可打开行程并切换面板和抽屉', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByTestId('floating-cards')).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await registerViaUi(page)
  await expect(page.getByRole('tab', { name: '酒店' })).toHaveCount(0)
  await page.getByRole('button', { name: '查看行程' }).click()
  const sheet = page.getByRole('dialog', { name: '查看行程' })
  await expect(sheet).toBeVisible()
  expect(await sheet.locator('[data-on-ink]').first().evaluate(el => getComputedStyle(el).touchAction)).not.toBe('none')
  await sheet.getByRole('tab', { name: '酒店', exact: true }).click()
  await expect(sheet.getByText('住在哪')).toBeVisible()
  await expectNoSeriousViolations(page)
  await page.screenshot({ path: testInfo.outputPath('mobile-hotels.png'), fullPage: true })
  const handle = await page.getByTestId('sheet-handle').boundingBox()
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y + handle!.height / 2)
  await page.mouse.down()
  await page.mouse.move(handle!.x + handle!.width / 2, handle!.y + 300, { steps: 12 })
  await page.mouse.up()
  await expect(sheet).toBeHidden()
  await page.getByRole('button', { name: '查看行程' }).click()
  await sheet.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(sheet).toBeHidden()
  await page.getByRole('button', { name: '历史对话' }).click()
  const drawer = page.getByRole('dialog', { name: '历史对话' })
  await expect(drawer).toBeVisible()
  await expect.poll(async () => (await drawer.boundingBox())!.width).toBeCloseTo(375, -1)
})
